<?xml version="1.0"?>
<package format="3">
  <name>whill_nav2_bringup</name>
  <version>0.0.1</version>
  <description>WHILL Nav2 bringup package</description>
  <maintainer email="ed26002@nda.ac.jp">selab</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>pointcloud_to_laserscan</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>pointcloud_to_laserscan</exec_depend>
  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
